### ISSUE TITLE
Can not drag selected text

### ISSUE THREAD

**Issue by Mart-Bogdan** [eyelash/xi-gtk#68] opened 2019-07-01 20:59 UTC
when I have text selected and drag using bouse I'm getting following errors in console
```
[2019-07-01][23:57:31][xi_core_lib::view][WARN] Usage of drag is deprecated; use gesture instead
```

Right mouse click is also not supported ( so can't copy

**Comment by eyelash** [comment] 2019-07-02 14:53
> Right mouse click is also not supported ( so can't copy

See #24. You can copy by pressing <kbd>ctrl</kbd>+<kbd>C</kbd>.

**Comment by Mart-Bogdan** [comment] 2019-07-02 17:57
@eyelash indeed I can. I've figured out ctrl+c, but it would be natural to drag using muse.

**Comment by eyelash** [comment] 2019-07-03 09:46
This seems to be a duplicate of #12.

**Closed by eyelash** 2019-07-03 09:46 UTC
