### ISSUE TITLE
Error building under Arch Linux

### ISSUE THREAD

**Issue by beefsack** [eyelash/xi-gtk#29] opened 2017-06-16 06:41 UTC
I'm currently getting `Unknown option -lm` when trying to build under Arch Linux. Full output below:

```
mick@mick-pc ~/D/xi-gtk (master)> mkdir build
mick@mick-pc ~/D/xi-gtk (master)> cd build/
mick@mick-pc ~/D/x/build (master)> meson ..
The Meson build system
Version: 0.41.0
Source dir: /home/mick/Development/xi-gtk
Build dir: /home/mick/Development/xi-gtk/build
Build type: native build
Project name: xi-gtk
Native c compiler: cc (gcc 7.1.1)
Native vala compiler: valac (valac 0.36.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Native dependency gtk+-3.0 found: YES 3.22.15
Native dependency json-glib-1.0 found: YES 1.2.8
Native dependency gio-unix-2.0 found: YES 2.52.2
Library m found: YES
Native dependency glib-2.0 found: YES 2.52.2
Build targets in project: 3
mick@mick-pc ~/D/x/build (master)> ninja
[1/16] Compiling Vala source ../src/Application.vala ../src/Blinker.vala ../src/CoreConnectio...otebook.vala ../src/Style.vala ../src/StyleMap.vala ../src/Utilities.vala ../src/Window.vala.
FAILED: xi-gtk@exe/Application.c xi-gtk@exe/Blinker.c xi-gtk@exe/CoreConnection.c xi-gtk@exe/EditView.c xi-gtk@exe/Line.c xi-gtk@exe/LineCache.c xi-gtk@exe/Notebook.c xi-gtk@exe/Style.c xi-gtk@exe/StyleMap.c xi-gtk@exe/Utilities.c xi-gtk@exe/Window.c 
valac -C --debug -lm --pkg gio-unix-2.0 --pkg json-glib-1.0 --pkg gtk+-3.0 -d xi-gtk@exe --gresources=../resources/gresource.xml ../src/Application.vala ../src/Blinker.vala ../src/CoreConnection.vala ../src/EditView.vala ../src/Line.vala ../src/LineCache.vala ../src/Notebook.vala ../src/Style.vala ../src/StyleMap.vala ../src/Utilities.vala ../src/Window.vala
Unknown option -lm
Run 'valac --help' to see a full list of available command line options.
[3/16] Generating resources_c with a custom command.
ninja: build stopped: subcommand failed.
mick@mick-pc ~/D/x/build (master) [1]> valac --version
Vala 0.36.3
mick@mick-pc ~/D/x/build (master)> uname -r
4.11.3-1-ARCH
mick@mick-pc ~/D/x/build (master)> lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

Have had a bit of a search around `valac` and `-lm` but I can't actually see the flag documented as one or as separate character flags.

**Comment by eyelash** [comment] 2017-06-16 07:25
This seems to be a regression with Meson version 0.41.0

**Comment by eyelash** [comment] 2017-06-16 07:27
See mesonbuild/meson#1939

**Comment by beefsack** [comment] 2017-06-16 07:27
I've just confirmed that's the version I'm on:

```
mick@mick-pc ~/D/b/acquire (master)> meson -v
0.41.0
```

**Comment by beefsack** [comment] 2017-06-16 07:28
> See mesonbuild/meson#1939

Looks like it, shall we close this issue?

**Comment by eyelash** [comment] 2017-06-16 07:32
Let's keep this issue open until the problem is fixed in Arch.

**Closed** 2017-06-20 16:28 UTC

**Comment by beefsack** [comment] 2017-06-20 23:19
Just tested and builds fine now 👍

The frontend is looking great by the way, keep up the great work!

**Comment by eyelash** [comment] 2017-06-21 06:38
Thanks for the kind words :)
